# -*- coding: utf-8 -*-
"""Integrity-Risk-Extraction-Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUtR9XrbBX6gxeyAKifmh0RWMFCL8r0I
"""

import pandas as pd
import requests
from io import StringIO
import time

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
}
todas_las_tablas = []
pagina = 1

print("Iniciando la extracción con freno automático...")

while True:
    print(f"Extrayendo página {pagina}...")
    url = f"https://www.scimagoiris.com/integrity-risk-indicators.php?page={pagina}"

    respuesta = requests.get(url, headers=headers)

    try:
        tablas = pd.read_html(StringIO(respuesta.text))

        if len(tablas) == 0:
            print("No se encontraron más tablas.")
            break

        df_temporal = tablas[0]

        # Limpieza básica
        df_temporal = df_temporal.dropna(subset=['Institution']).copy()
        df_temporal['Institution'] = df_temporal['Institution'].str.replace(r'\d+$', '', regex=True).str.strip()

        # --- EL FRENO INTELIGENTE ---
        # Si ya tenemos tablas guardadas, comparamos esta nueva con la anterior
        if len(todas_las_tablas) > 0:
            primera_uni_actual = df_temporal.iloc[0]['Institution']
            primera_uni_anterior = todas_las_tablas[-1].iloc[0]['Institution']

            if primera_uni_actual == primera_uni_anterior:
                print(f"\n¡Freno activado en la página {pagina}! La web empezó a repetir datos.")
                break # Rompe el bucle infinito
        # ----------------------------

        todas_las_tablas.append(df_temporal)
        pagina += 1
        time.sleep(1)

    except ValueError:
        print("Fin de los datos detectado.")
        break

# Unimos y guardamos
if todas_las_tablas:
    df_final = pd.concat(todas_las_tablas, ignore_index=True)

    columnas_basura = ['Unnamed: 0', 'Details']
    df_final = df_final.drop(columns=[col for col in columnas_basura if col in df_final.columns])

    # Nos aseguramos de eliminar cualquier duplicado accidental que se haya colado
    df_final = df_final.drop_duplicates(subset=['Institution'])

    print("\n" + "="*40)
    print(f"¡Éxito! Se han extraído {len(df_final)} instituciones únicas en total.")
    print("="*40)

    df_final.to_csv("Scimago_IRIS_Index_Data.csv", index=False)
    print("El archivo 'Scimago_IRIS_Index_Data.csv' está listo en tu carpeta lateral.")
else:
    print("No se logró extraer ninguna información.")